name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or your preferred version
      - name: Install dependencies
        run: npm install
      - name: Make Jest executable
        run: chmod +x ./node_modules/.bin/jest
      - name: Run tests
        run: npm test
